services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: w-flow-mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: w_flow
      MYSQL_USER: wflow
      MYSQL_PASSWORD: wflow123
      TZ: Asia/Shanghai
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
